### ISSUE TITLE
Add Zcash URI parser

### ISSUE THREAD

**Issue by pacu** [Electric-Coin-Company/zcash-swift-wallet-sdk#360] opened 2022-04-05 14:49 UTC
## Is your feature request related to a problem? Please describe.
we need a parser for https://zips.z.cash/zip-0321

## Describe the solution you'd like
A parser has been [implemented in Rust](https://github.com/zcash/librustzcash/blob/master/zcash_client_backend/src/zip321.rs), so ideally the SDK would expose a Kotlin API for the app to consume this.

**Comment by nuttycom** [comment] 2024-04-09 15:33
Duplicate of #320

**Closed** 2024-04-09 15:33 UTC
