### ISSUE TITLE
Release zcash-swift-wallet-sdk version 2.2.0

### ISSUE THREAD

**Issue by nuttycom** [Electric-Coin-Company/zcash-swift-wallet-sdk#1410] opened 2024-04-09 13:45 UTC

**Comment by daira** [comment] 2024-10-04 17:38
Version 2.2.3 was released in #1490. It looks like the DAG is out-of-date and could do with some love and attention.

**Comment by str4d** [comment] 2024-10-31 05:40
Yep. @LukasKorba opened #1479 as a duplicate of this issue, and tied #1490 to that instead. I've manually fixed the DAG to point to that issue instead.

We really need to be in agreement about how these release issues get managed; having multiple issues for the same release causes significant problems in the DAG.

**Closed by str4d** 2024-10-31 05:40 UTC
